[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\temp\vs_cds\chassis_timesync_custom_device'

[projects.cd]
path = 'Source\Chassis TimeSync Custom Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'PharLap Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Pharlap'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Linux x64'
build_spec = 'Engine Release'

[package]
type = 'nipkg'
name = 'chassis-timesync-custom-device-{veristand_version}'
dev_xml_path = 'Source\Timing and Sync Chassis TimeSync.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Timing and Sync'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2015_release_branches = ["master",]
2016_release_branches = ["master",]
2017_release_branches = ["master",]
2018_release_branches = ["master",]
